const countries = [
	{ value: "", optionName: "Select a country / region…" },
	{ value: "AF", optionName: "Afghanistan" },
	{ value: "AX", optionName: "Åland Islands" },
	{ value: "AL", optionName: "Albania" },
	{ value: "DZ", optionName: "Algeria" },
	{ value: "AS", optionName: "American Samoa" },
	{ value: "AD", optionName: "Andorra" },
	{ value: "AO", optionName: "Angola" },
	{ value: "AI", optionName: "Anguilla" },
	{ value: "AQ", optionName: "Antarctica" },
	{ value: "AG", optionName: "Antigua and Barbuda" },
	{ value: "AR", optionName: "Argentina" },
	{ value: "AM", optionName: "Armenia" },
	{ value: "AW", optionName: "Aruba" },
	{ value: "AU", optionName: "Australia" },
	{ value: "AT", optionName: "Austria" },
	{ value: "AZ", optionName: "Azerbaijan" },
	{ value: "BS", optionName: "Bahamas" },
	{ value: "BH", optionName: "Bahrain" },
	{ value: "BD", optionName: "Bangladesh" },
	{ value: "BB", optionName: "Barbados" },
	{ value: "BY", optionName: "Belarus" },
	{ value: "PW", optionName: "Belau" },
	{ value: "BE", optionName: "Belgium" },
	{ value: "BZ", optionName: "Belize" },
	{ value: "BJ", optionName: "Benin" },
	{ value: "BM", optionName: "Bermuda" },
	{ value: "BT", optionName: "Bhutan" },
	{ value: "BO", optionName: "Bolivia" },
	{ value: "BQ", optionName: "Bonaire, Saint Eustatius and Saba" },
	{ value: "BA", optionName: "Bosnia and Herzegovina" },
	{ value: "BW", optionName: "Botswana" },
	{ value: "BV", optionName: "Bouvet Island" },
	{ value: "BR", optionName: "Brazil" },
	{ value: "IO", optionName: "British Indian Ocean Territory" },
	{ value: "BN", optionName: "Brunei" },
	{ value: "BG", optionName: "Bulgaria" },
	{ value: "BF", optionName: "Burkina Faso" },
	{ value: "BI", optionName: "Burundi" },
	{ value: "KH", optionName: "Cambodia" },
	{ value: "CM", optionName: "Cameroon" },
	{ value: "CA", optionName: "Canada" },
	{ value: "CV", optionName: "Cape Verde" },
	{ value: "KY", optionName: "Cayman Islands" },
	{ value: "CF", optionName: "Central African Republic" },
	{ value: "TD", optionName: "Chad" },
	{ value: "CL", optionName: "Chile" },
	{ value: "CN", optionName: "China" },
	{ value: "CX", optionName: "Christmas Island" },
	{ value: "CC", optionName: "Cocos (Keeling) Islands" },
	{ value: "CO", optionName: "Colombia" },
	{ value: "KM", optionName: "Comoros" },
	{ value: "CG", optionName: "Congo (Brazzaville)" },
	{ value: "CD", optionName: "Congo (Kinshasa)" },
	{ value: "CK", optionName: "Cook Islands" },
	{ value: "CR", optionName: "Costa Rica" },
	{ value: "HR", optionName: "Croatia" },
	{ value: "CU", optionName: "Cuba" },
	{ value: "CW", optionName: "Curaçao" },
	{ value: "CY", optionName: "Cyprus" },
	{ value: "CZ", optionName: "Czech Republic" },
	{ value: "DK", optionName: "Denmark" },
	{ value: "DJ", optionName: "Djibouti" },
	{ value: "DM", optionName: "Dominica" },
	{ value: "DO", optionName: "Dominican Republic" },
	{ value: "EC", optionName: "Ecuador" },
	{ value: "EG", optionName: "Egypt" },
	{ value: "SV", optionName: "El Salvador" },
	{ value: "GQ", optionName: "Equatorial Guinea" },
	{ value: "ER", optionName: "Eritrea" },
	{ value: "EE", optionName: "Estonia" },
	{ value: "SZ", optionName: "Eswatini" },
	{ value: "ET", optionName: "Ethiopia" },
	{ value: "FK", optionName: "Falkland Islands" },
	{ value: "FO", optionName: "Faroe Islands" },
	{ value: "FJ", optionName: "Fiji" },
	{ value: "FI", optionName: "Finland" },
	{ value: "FR", optionName: "France" },
	{ value: "GF", optionName: "French Guiana" },
	{ value: "PF", optionName: "French Polynesia" },
	{ value: "TF", optionName: "French Southern Territories" },
	{ value: "GA", optionName: "Gabon" },
	{ value: "GM", optionName: "Gambia" },
	{ value: "GE", optionName: "Georgia" },
	{ value: "DE", optionName: "Germany" },
	{ value: "GH", optionName: "Ghana" },
	{ value: "GI", optionName: "Gibraltar" },
	{ value: "GR", optionName: "Greece" },
	{ value: "GL", optionName: "Greenland" },
	{ value: "GD", optionName: "Grenada" },
	{ value: "GP", optionName: "Guadeloupe" },
	{ value: "GU", optionName: "Guam" },
	{ value: "GT", optionName: "Guatemala" },
	{ value: "GG", optionName: "Guernsey" },
	{ value: "GN", optionName: "Guinea" },
	{ value: "GW", optionName: "Guinea-Bissau" },
	{ value: "GY", optionName: "Guyana" },
	{ value: "HT", optionName: "Haiti" },
	{ value: "HM", optionName: "Heard Island and McDonald Islands" },
	{ value: "HN", optionName: "Honduras" },
	{ value: "HK", optionName: "Hong Kong" },
	{ value: "HU", optionName: "Hungary" },
	{ value: "IS", optionName: "Iceland" },
	{ value: "IN", optionName: "India" },
	{ value: "ID", optionName: "Indonesia" },
	{ value: "IR", optionName: "Iran" },
	{ value: "IQ", optionName: "Iraq" },
	{ value: "IE", optionName: "Ireland" },
	{ value: "IM", optionName: "Isle of Man" },
	{ value: "IL", optionName: "Israel" },
	{ value: "IT", optionName: "Italy" },
	{ value: "CI", optionName: "Ivory Coast" },
	{ value: "JM", optionName: "Jamaica" },
	{ value: "JP", optionName: "Japan" },
	{ value: "JE", optionName: "Jersey" },
	{ value: "JO", optionName: "Jordan" },
	{ value: "KZ", optionName: "Kazakhstan" },
	{ value: "KE", optionName: "Kenya" },
	{ value: "KI", optionName: "Kiribati" },
	{ value: "KW", optionName: "Kuwait" },
	{ value: "KG", optionName: "Kyrgyzstan" },
	{ value: "LA", optionName: "Laos" },
	{ value: "LV", optionName: "Latvia" },
	{ value: "LB", optionName: "Lebanon" },
	{ value: "LS", optionName: "Lesotho" },
	{ value: "LR", optionName: "Liberia" },
	{ value: "LY", optionName: "Libya" },
	{ value: "LI", optionName: "Liechtenstein" },
	{ value: "LT", optionName: "Lithuania" },
	{ value: "LU", optionName: "Luxembourg" },
	{ value: "MO", optionName: "Macao" },
	{ value: "MG", optionName: "Madagascar" },
	{ value: "MW", optionName: "Malawi" },
	{ value: "MY", optionName: "Malaysia" },
	{ value: "MV", optionName: "Maldives" },
	{ value: "ML", optionName: "Mali" },
	{ value: "MT", optionName: "Malta" },
	{ value: "MH", optionName: "Marshall Islands" },
	{ value: "MQ", optionName: "Martinique" },
	{ value: "MR", optionName: "Mauritania" },
	{ value: "MU", optionName: "Mauritius" },
	{ value: "YT", optionName: "Mayotte" },
	{ value: "MX", optionName: "Mexico" },
	{ value: "FM", optionName: "Micronesia" },
	{ value: "MD", optionName: "Moldova" },
	{ value: "MC", optionName: "Monaco" },
	{ value: "MN", optionName: "Mongolia" },
	{ value: "ME", optionName: "Montenegro" },
	{ value: "MS", optionName: "Montserrat" },
	{ value: "MA", optionName: "Morocco" },
	{ value: "MZ", optionName: "Mozambique" },
	{ value: "MM", optionName: "Myanmar" },
	{ value: "NA", optionName: "Namibia" },
	{ value: "NR", optionName: "Nauru" },
	{ value: "NP", optionName: "Nepal" },
	{ value: "NL", optionName: "Netherlands" },
	{ value: "NC", optionName: "New Caledonia" },
	{ value: "NZ", optionName: "New Zealand" },
	{ value: "NI", optionName: "Nicaragua" },
	{ value: "NE", optionName: "Niger" },
	{ value: "NG", optionName: "Nigeria" },
	{ value: "NU", optionName: "Niue" },
	{ value: "NF", optionName: "Norfolk Island" },
	{ value: "KP", optionName: "North Korea" },
	{ value: "MK", optionName: "North Macedonia" },
	{ value: "MP", optionName: "Northern Mariana Islands" },
	{ value: "NO", optionName: "Norway" },
	{ value: "OM", optionName: "Oman" },
	{ value: "PK", optionName: "Pakistan" },
	{ value: "PS", optionName: "Palestinian Territory" },
	{ value: "PA", optionName: "Panama" },
	{ value: "PG", optionName: "Papua New Guinea" },
	{ value: "PY", optionName: "Paraguay" },
	{ value: "PE", optionName: "Peru" },
	{ value: "PH", optionName: "Philippines" },
	{ value: "PN", optionName: "Pitcairn" },
	{ value: "PL", optionName: "Poland" },
	{ value: "PT", optionName: "Portugal" },
	{ value: "PR", optionName: "Puerto Rico" },
	{ value: "QA", optionName: "Qatar" },
	{ value: "RE", optionName: "Reunion" },
	{ value: "RO", optionName: "Romania" },
	{ value: "RU", optionName: "Russia" },
	{ value: "RW", optionName: "Rwanda" },
	{ value: "ST", optionName: "São Tomé and Príncipe" },
	{ value: "BL", optionName: "Saint Barthélemy" },
	{ value: "SH", optionName: "Saint Helena" },
	{ value: "KN", optionName: "Saint Kitts and Nevis" },
	{ value: "LC", optionName: "Saint Lucia" },
	{ value: "SX", optionName: "Saint Martin (Dutch part)" },
	{ value: "MF", optionName: "Saint Martin (French part)" },
	{ value: "PM", optionName: "Saint Pierre and Miquelon" },
	{ value: "VC", optionName: "Saint Vincent and the Grenadines" },
	{ value: "WS", optionName: "Samoa" },
	{ value: "SM", optionName: "San Marino" },
	{ value: "SA", optionName: "Saudi Arabia" },
	{ value: "SN", optionName: "Senegal" },
	{ value: "RS", optionName: "Serbia" },
	{ value: "SC", optionName: "Seychelles" },
	{ value: "SL", optionName: "Sierra Leone" },
	{ value: "SG", optionName: "Singapore" },
	{ value: "SK", optionName: "Slovakia" },
	{ value: "SI", optionName: "Slovenia" },
	{ value: "SB", optionName: "Solomon Islands" },
	{ value: "SO", optionName: "Somalia" },
	{ value: "ZA", optionName: "South Africa" },
	{ value: "GS", optionName: "South Georgia/Sandwich Islands" },
	{ value: "KR", optionName: "South Korea" },
	{ value: "SS", optionName: "South Sudan" },
	{ value: "ES", optionName: "Spain" },
	{ value: "LK", optionName: "Sri Lanka" },
	{ value: "SD", optionName: "Sudan" },
	{ value: "SR", optionName: "Suriname" },
	{ value: "SJ", optionName: "Svalbard and Jan Mayen" },
	{ value: "SE", optionName: "Sweden" },
	{ value: "CH", optionName: "Switzerland" },
	{ value: "SY", optionName: "Syria" },
	{ value: "TW", optionName: "Taiwan" },
	{ value: "TJ", optionName: "Tajikistan" },
	{ value: "TZ", optionName: "Tanzania" },
	{ value: "TH", optionName: "Thailand" },
	{ value: "TL", optionName: "Timor-Leste" },
	{ value: "TG", optionName: "Togo" },
	{ value: "TK", optionName: "Tokelau" },
	{ value: "TO", optionName: "Tonga" },
	{ value: "TT", optionName: "Trinidad and Tobago" },
	{ value: "TN", optionName: "Tunisia" },
	{ value: "TR", optionName: "Turkey" },
	{ value: "TM", optionName: "Turkmenistan" },
	{ value: "TC", optionName: "Turks and Caicos Islands" },
	{ value: "TV", optionName: "Tuvalu" },
	{ value: "UG", optionName: "Uganda" },
	{ value: "UA", optionName: "Ukraine" },
	{ value: "AE", optionName: "United Arab Emirates" },
	{ value: "GB", optionName: "United Kingdom (UK)" },
	{ value: "US", optionName: "United States (US)" },
	{ value: "UM", optionName: "United States (US) Minor Outlying Islands" },
	{ value: "UY", optionName: "Uruguay" },
	{ value: "UZ", optionName: "Uzbekistan" },
	{ value: "VU", optionName: "Vanuatu" },
	{ value: "VA", optionName: "Vatican" },
	{ value: "VE", optionName: "Venezuela" },
	{ value: "VN", optionName: "Vietnam" },
	{ value: "VG", optionName: "Virgin Islands (British)" },
	{ value: "VI", optionName: "Virgin Islands (US)" },
	{ value: "WF", optionName: "Wallis and Futuna" },
	{ value: "EH", optionName: "Western Sahara" },
	{ value: "YE", optionName: "Yemen" },
	{ value: "ZM", optionName: "Zambia" },
	{ value: "ZW", optionName: "Zimbabwe" },
];

const getCountries = () => {
	return countries;
};

export default getCountries;
